services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: mahdi
      POSTGRES_PASSWORD: Mahdi1384arabi@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahdi"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

  web:
    build: ./backend
    image: django-app
    container_name: web
    command: gunicorn calender.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - static_volume:/app/django-project/staticfiles
      - media_volume:/app/django-project/media
    restart: unless-stopped

  celery:
    image: django-app
    container_name: celery
    command: celery -A calender worker -l info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  celery-beat:
    image: django-app
    container_name: celery-beat
    command: celery -A calender beat -l info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
