# Generated by Django 6.0.2 on 2026-02-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
