# Generated by Django 6.0.2 on 2026-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_task_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
